### ISSUE TITLE
Questions about how to reproduce Nerf result  in stanford dataset?

### ISSUE THREAD

**Issue by Gardlin** [facebookresearch/neural-light-fields#3]
Hi , thanks for your great work , I  have some questions about how to  reproduce the baselinee nerf result  in stanfor dataset.

I  followed your code in  in baselines/nerf_tensorflow  and  only  modify the config file ''stanford_config.txt''  with  facotr=1 , but result seems not very good .
First it  only get 19.2 PSNR  when train for 200k iterations , when training more iterations , it improved very little  which is still much lower  than the result in your paper. 
![image](https://user-images.githubusercontent.com/28174084/174846901-4a81a28d-0534-4ea7-8c8e-f83515b2431d.png)

And how much iterations should I run. The total  iterations in your code  is 1000, 000 and  it runs very slow.

I'm wondering  how I can get  the  baseline result, it will be very grateful.

**Comment by benattal** [comment]
Hi! A few questions:

1) Are you using our stanford_half data provided [here](https://drive.google.com/drive/folders/1MnniS2uk5vIQ4XtzVSbD-CY7oEZQoL-2)? What scene are you testing on?
2) Did you make any changes to the nerf_tensorflow codebase?
3) Did you change any other configuration options apart from factor=1 ?

**Comment by Gardlin** [comment]
1. I'm using stanford_half you provided. And I have tested on  chess ,tarot_small  and tarot_large scenes , while  the  result  on chess  scene seems  same with your paper,  the  PSNR  results on tarot_small and tarot_large  is  much lower than the result in the paer. I  only  put  those images  in an  new folder name images  so that nerf_tensorflow can  work.
2. When I change  configuration with factor=1 , I have to  modify some code to make it  run, I  add two lines of code below here
https://github.com/facebookresearch/neural-light-fields/blob/1667d88ca902bed3cc4e2d0d51029cb38a2e7a26/baselines/third_party/nerf_tensorflow/load_stanford.py#L35
```
        width = int(np.round(sh[1] / factor))
        height = int(np.round(sh[0] / factor))
```
3. No other configurations was changed
4.  Besides  , nerf_tensorflow  converges very fast  on  chess scene ,it get 41 PSNR after 200k iterations , while  it  converges  extremely slow  on  tarot_small/large  scene ,  which only get  19.5 PSNR  after running 200k iterations.

**Comment by benattal** [comment]
That's quite odd. Both the tarot_small and tarot_large models exceed 20dB training PSNR fairly quickly for me, and after training for longer I am able to reproduce the paper results. Here are examples of predicted validation images after about ~30k iters for both tarot and tarot_small.

![027500_tarot](https://user-images.githubusercontent.com/2993881/177011674-021e3c77-5de6-455f-8abb-20d3e9620e15.png)
![027500_tarot_small](https://user-images.githubusercontent.com/2993881/177011678-20602c4e-c666-4bb4-8651-58af7049f537.png)



What command are you using to run NeRF? Are you changing the checkpointing / log directory each time you run an experiment? If not, you may be accidentally loading the weights and optimizer state from a previous scene (which could negatively impact performance). 

For example, I am running:

`python run_nerf.py --config configs/stanford_config.txt --datadir ~/data/stanford_half/tarot --expname nerf_tarot`

Changing the `--expname` argument will change the checkpointing / log directory.

**Comment by benattal** [comment]
Did you manage to resolve the issue?

**Comment by Gardlin** [comment]
Yes . When I  delete the old experiment directory and train from scratch , it sucessfully reproduce  the  near  result  with yours.
Maybe I forget to change the exp_name at first and  it  loads the false weights, and the false initialize weights harms a lot  to the training.

**Comment by benattal** [comment]
Okay great! I'll add some more explicit instructions about how to run this baseline in the README.
